;; assertion-catalog.scm - Auto-generated kernel assertion catalog
;; Generated by extract-assertions.sh
;; DO NOT EDIT - regenerate with: ./docs/rfc/extract-assertions.sh

(define *assertion-catalog*
  '(
    ;; === Instrumentation Points (session-stat!) ===
    (instrumentation bytes-in "./gossip.scm" 164)
    (instrumentation bytes-out "./gossip.scm" 154)
    (instrumentation bytes-written "./vault.scm" 503)
    (instrumentation commits "./cyberspace-repl.scm" 4577)
    (instrumentation federation-changes "./cyberspace-repl.scm" 4608)
    (instrumentation gossip-exchanges "./cyberspace-repl.scm" 4775)
    (instrumentation hashes "./vault.scm" 1868)
    (instrumentation mdns-messages "./mdns.scm" 128)
    (instrumentation packets-ipv "./gossip.scm" 170)
    (instrumentation peers-discovered "./cyberspace-repl.scm" 4767)
    (instrumentation queries "./cyberspace-repl.scm" 5078)
    (instrumentation reads "./vault.scm" 1194)
    (instrumentation seals "./cyberspace-repl.scm" 4578)
    (instrumentation signs "./cyberspace-repl.scm" 4588)
    (instrumentation syncs "./cyberspace-repl.scm" 903)
    (instrumentation unlocks "./vault.scm" 308)
    (instrumentation verifies "./cyberspace-repl.scm" 4593)
    (instrumentation votes "./cyberspace-repl.scm" 976)
    (instrumentation wormholes "./cyberspace-repl.scm" 1462)
    (instrumentation writes "./vault.scm" 502)

    ;; === Security Errors ===
    (security-error capability-amplification "./cyberspace-repl.scm" 1504)
    (security-error confidentiality-violation "./cyberspace-repl.scm" 1719)
    (security-error delegate-denied "./cyberspace-repl.scm" 1754)
    (security-error delete-denied "./cyberspace-repl.scm" 1751)
    (security-error integrity-violation "./cyberspace-repl.scm" 1723)
    (security-error no-ambient-authority "./cyberspace-repl.scm" 1740)
    (security-error read-denied "./cyberspace-repl.scm" 1745)
    (security-error secure-clear "./cyberspace-repl.scm" 1913)
    (security-error secure-clear-failed "./cyberspace-repl.scm" 1901)
    (security-error write-denied "./cyberspace-repl.scm" 1748)

    ;; === Precondition Guards ===
    (precondition directory-exists? keystore-path "./enroll.scm" 501)
    (precondition directory-exists? ".forge" "./cyberspace-repl.scm" 197)
    (precondition chaotic? thing "./cyberspace-repl.scm" 603)
    (precondition attested? "./cyberspace-repl.scm" 702)
    (precondition quiescent? memo "./cyberspace-repl.scm" 806)
    (precondition attested? "./cyberspace-repl.scm" 1161)
    (precondition attested? "./cyberspace-repl.scm" 1189)
    (precondition directory-exists? ".vault/keys" "./cyberspace-repl.scm" 3373)
    (precondition directory-exists? output-dir "./spki-keygen.scm" 83)
    (precondition directory-exists? path "./keyring.scm" 76)
    (precondition directory-exists? ks-dir "./vault.scm" 227)
    (precondition keystore-exists? "./vault.scm" 280)
    (precondition directory-exists? ".vault" "./vault.scm" 398)
))

;; Summary counts
(define (assertion-summary)
  (let ((instrs (filter (lambda (a) (eq? (car a) 'instrumentation)) *assertion-catalog*))
        (errors (filter (lambda (a) (eq? (car a) 'security-error)) *assertion-catalog*))
        (guards (filter (lambda (a) (eq? (car a) 'precondition)) *assertion-catalog*)))
    `((instrumentation-points . ,(length instrs))
      (security-errors . ,(length errors))
      (precondition-guards . ,(length guards))
      (total . ,(length *assertion-catalog*)))))
