;; assertion-catalog.scm - Auto-generated kernel assertion catalog
;; Generated by extract-assertions.sh
;; DO NOT EDIT - regenerate with: ./docs/rfc/extract-assertions.sh

(define *assertion-catalog*
  '(
    ;; === Instrumentation Points (session-stat!) ===
    (instrumentation bytes-in "./gossip.scm" 164)
    (instrumentation bytes-out "./gossip.scm" 154)
    (instrumentation bytes-written "./vault.scm" 503)
    (instrumentation commits "./cyberspace-repl.scm" 4716)
    (instrumentation federation-changes "./cyberspace-repl.scm" 4747)
    (instrumentation gossip-exchanges "./cyberspace-repl.scm" 4997)
    (instrumentation hashes "./vault.scm" 1868)
    (instrumentation mdns-messages "./mdns.scm" 128)
    (instrumentation packets-ipv "./gossip.scm" 170)
    (instrumentation peers-discovered "./cyberspace-repl.scm" 4989)
    (instrumentation queries "./cyberspace-repl.scm" 5300)
    (instrumentation reads "./vault.scm" 1194)
    (instrumentation seals "./cyberspace-repl.scm" 4717)
    (instrumentation signs "./cyberspace-repl.scm" 4727)
    (instrumentation syncs "./cyberspace-repl.scm" 1040)
    (instrumentation unlocks "./vault.scm" 308)
    (instrumentation verifies "./cyberspace-repl.scm" 4732)
    (instrumentation votes "./cyberspace-repl.scm" 1113)
    (instrumentation wormholes "./cyberspace-repl.scm" 1599)
    (instrumentation writes "./vault.scm" 502)

    ;; === Security Errors ===
    (security-error capability-amplification "./cyberspace-repl.scm" 1641)
    (security-error confidentiality-violation "./cyberspace-repl.scm" 1856)
    (security-error delegate-denied "./cyberspace-repl.scm" 1891)
    (security-error delete-denied "./cyberspace-repl.scm" 1888)
    (security-error integrity-violation "./cyberspace-repl.scm" 1860)
    (security-error no-ambient-authority "./cyberspace-repl.scm" 1877)
    (security-error read-denied "./cyberspace-repl.scm" 1882)
    (security-error secure-clear "./cyberspace-repl.scm" 2050)
    (security-error secure-clear-failed "./cyberspace-repl.scm" 2038)
    (security-error write-denied "./cyberspace-repl.scm" 1885)

    ;; === Precondition Guards ===
    (precondition directory-exists? keystore-path "./enroll.scm" 501)
    (precondition directory-exists? ".forge" "./cyberspace-repl.scm" 237)
    (precondition chaotic? thing "./cyberspace-repl.scm" 740)
    (precondition attested? "./cyberspace-repl.scm" 839)
    (precondition quiescent? memo "./cyberspace-repl.scm" 943)
    (precondition attested? "./cyberspace-repl.scm" 1298)
    (precondition attested? "./cyberspace-repl.scm" 1326)
    (precondition directory-exists? ".vault/keys" "./cyberspace-repl.scm" 3510)
    (precondition directory-exists? output-dir "./spki-keygen.scm" 83)
    (precondition directory-exists? path "./keyring.scm" 76)
    (precondition directory-exists? ks-dir "./vault.scm" 227)
    (precondition keystore-exists? "./vault.scm" 280)
    (precondition directory-exists? ".vault" "./vault.scm" 398)
))

;; Summary counts
(define (assertion-summary)
  (let ((instrs (filter (lambda (a) (eq? (car a) 'instrumentation)) *assertion-catalog*))
        (errors (filter (lambda (a) (eq? (car a) 'security-error)) *assertion-catalog*))
        (guards (filter (lambda (a) (eq? (car a) 'precondition)) *assertion-catalog*)))
    `((instrumentation-points . ,(length instrs))
      (security-errors . ,(length errors))
      (precondition-guards . ,(length guards))
      (total . ,(length *assertion-catalog*)))))
