;; assertion-catalog.scm - Auto-generated kernel assertion catalog
;; Generated by extract-assertions.sh
;; DO NOT EDIT - regenerate with: ./docs/rfc/extract-assertions.sh

(define *assertion-catalog*
  '(
    ;; === Instrumentation Points (session-stat!) ===
    (instrumentation bytes-in "./gossip.scm" 164)
    (instrumentation bytes-out "./gossip.scm" 154)
    (instrumentation commits "./cyberspace-repl.scm" 4406)
    (instrumentation federation-changes "./cyberspace-repl.scm" 4437)
    (instrumentation gossip-exchanges "./cyberspace-repl.scm" 4582)
    (instrumentation hashes "./vault.scm" 1851)
    (instrumentation mdns-messages "./mdns.scm" 128)
    (instrumentation packets-ipv "./gossip.scm" 170)
    (instrumentation peers-discovered "./cyberspace-repl.scm" 4574)
    (instrumentation queries "./cyberspace-repl.scm" 4885)
    (instrumentation reads "./vault.scm" 1177)
    (instrumentation seals "./cyberspace-repl.scm" 4407)
    (instrumentation signs "./cyberspace-repl.scm" 4417)
    (instrumentation syncs "./cyberspace-repl.scm" 725)
    (instrumentation unlocks "./vault.scm" 291)
    (instrumentation verifies "./cyberspace-repl.scm" 4422)
    (instrumentation votes "./cyberspace-repl.scm" 798)
    (instrumentation wormholes "./cyberspace-repl.scm" 1284)

    ;; === Security Errors ===
    (security-error capability-amplification "./cyberspace-repl.scm" 1326)
    (security-error confidentiality-violation "./cyberspace-repl.scm" 1541)
    (security-error delegate-denied "./cyberspace-repl.scm" 1576)
    (security-error delete-denied "./cyberspace-repl.scm" 1573)
    (security-error integrity-violation "./cyberspace-repl.scm" 1545)
    (security-error no-ambient-authority "./cyberspace-repl.scm" 1562)
    (security-error read-denied "./cyberspace-repl.scm" 1567)
    (security-error secure-clear "./cyberspace-repl.scm" 1735)
    (security-error secure-clear-failed "./cyberspace-repl.scm" 1723)
    (security-error write-denied "./cyberspace-repl.scm" 1570)

    ;; === Precondition Guards ===
    (precondition directory-exists? keystore-path "./enroll.scm" 501)
    (precondition chaotic? thing "./cyberspace-repl.scm" 425)
    (precondition attested? "./cyberspace-repl.scm" 524)
    (precondition quiescent? memo "./cyberspace-repl.scm" 628)
    (precondition attested? "./cyberspace-repl.scm" 983)
    (precondition attested? "./cyberspace-repl.scm" 1011)
    (precondition directory-exists? ".vault/keys" "./cyberspace-repl.scm" 3204)
    (precondition directory-exists? output-dir "./spki-keygen.scm" 83)
    (precondition directory-exists? path "./keyring.scm" 76)
    (precondition directory-exists? ks-dir "./vault.scm" 210)
    (precondition keystore-exists? "./vault.scm" 263)
    (precondition directory-exists? ".vault" "./vault.scm" 381)
))

;; Summary counts
(define (assertion-summary)
  (let ((instrs (filter (lambda (a) (eq? (car a) 'instrumentation)) *assertion-catalog*))
        (errors (filter (lambda (a) (eq? (car a) 'security-error)) *assertion-catalog*))
        (guards (filter (lambda (a) (eq? (car a) 'precondition)) *assertion-catalog*)))
    `((instrumentation-points . ,(length instrs))
      (security-errors . ,(length errors))
      (precondition-guards . ,(length guards))
      (total . ,(length *assertion-catalog*)))))
