#!/bin/bash
# Generate RFC index with KWIC
# Auto-discovers all rfc-*.md and rfc-*.txt files

# Discover RFCs from filesystem (unique basenames, sorted by number)
discover_rfcs() {
  shopt -s nullglob
  for f in rfc-*.md rfc-*.txt; do
    [[ -f "$f" ]] && echo "${f%.*}"
  done | sort -u | sort -t- -k2,2n
}

# Check for duplicate RFC numbers
check_duplicates() {
  local prev_num=""
  local prev_rfc=""
  for rfc in "$@"; do
    local num=$(echo "$rfc" | sed 's/rfc-\([0-9]*\)-.*/\1/')
    if [[ -n "$prev_num" && "$num" == "$prev_num" ]]; then
      echo "WARNING: Duplicate RFC number $num:" >&2
      echo "  - $prev_rfc" >&2
      echo "  - $rfc" >&2
    fi
    prev_num="$num"
    prev_rfc="$rfc"
  done
}

# Build array from discovery
RFCS=()
while IFS= read -r rfc; do
  RFCS+=("$rfc")
done < <(discover_rfcs)

echo "Discovered ${#RFCS[@]} RFCs"
check_duplicates "${RFCS[@]}"

STOP_WORDS="a an and are as at be by for from has have in is it of on or the to was with"

is_stop_word() {
  local word=$(echo "$1" | tr '[:upper:]' '[:lower:]')
  for stop in $STOP_WORDS; do
    [[ "$word" == "$stop" ]] && return 0
  done
  return 1
}

get_title() {
  local base="$1"
  if [[ -f "${base}.txt" ]]; then
    head -1 "${base}.txt"
  elif [[ -f "${base}.md" ]]; then
    head -1 "${base}.md" | sed 's/^# //'
  else
    echo "$base"
  fi
}

# Start HTML
cat > index.html << 'HEADER'
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Library of Cyberspace - RFC Index</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      max-width: 900px;
      margin: 0 auto;
      padding: 2rem;
      line-height: 1.6;
      color: #333;
    }
    h1 { border-bottom: 2px solid #333; padding-bottom: 0.5rem; }
    table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
    th, td { padding: 0.5rem; text-align: left; border-bottom: 1px solid #ddd; }
    th { background: #f5f5f5; }
    .formats a { margin-right: 0.5rem; }
    .kwic { font-family: monospace; font-size: 0.85rem; }
    .kwic td { padding: 0.25rem 0.5rem; white-space: nowrap; }
    .kwic .left { text-align: right; color: #666; }
    .kwic .keyword { font-weight: bold; }
    .kwic .right { text-align: left; color: #666; }
    .kwic .rfc { text-align: left; }
  </style>
</head>
<body>
  <h1>Library of Cyberspace - RFC Index</h1>
  <p>Request for Comments documents for the Library of Cyberspace preservation architecture.</p>

  <table>
    <thead>
      <tr>
        <th>RFC</th>
        <th>Title</th>
        <th>Formats</th>
      </tr>
    </thead>
    <tbody>
HEADER

# Generate RFC table
for rfc in "${RFCS[@]}"; do
  title=$(get_title "$rfc")
  num=$(echo "$rfc" | sed -E 's/rfc-0*([0-9]+)-.*/\1/')
  formats='<a href="'"${rfc}"'.txt">Text</a> <a href="'"${rfc}"'.ps">PostScript</a> <a href="'"${rfc}"'.html">Hypertext</a>'

  cat >> index.html << EOF
      <tr>
        <td>${num}</td>
        <td>${title}</td>
        <td class="formats">${formats}</td>
      </tr>
EOF
done

cat >> index.html << 'MIDDLE'
    </tbody>
  </table>

  <h2>Permuted Index (KWIC)</h2>
  <p>Key Word In Context index for discovery by concept.</p>
  <table class="kwic">
    <tbody>
MIDDLE

# Generate KWIC entries
for rfc in "${RFCS[@]}"; do
  title=$(get_title "$rfc")
  # Strip "RFC-NNN: " prefix
  bare_title=$(echo "$title" | sed 's/^RFC-[0-9]*: //')
  words=($bare_title)
  num_words=${#words[@]}

  for ((i=0; i<num_words; i++)); do
    word="${words[$i]}"
    # Skip stop words
    is_stop_word "$word" && continue

    # Build left context
    left=""
    for ((j=0; j<i; j++)); do
      left="$left${words[$j]} "
    done

    # Build right context
    right=""
    for ((j=i+1; j<num_words; j++)); do
      right="$right ${words[$j]}"
    done

    num=$(echo "$rfc" | sed -E 's/rfc-0*([0-9]+)-.*/\1/')
    echo "${word}|${left}|${right}|${rfc}|${num}"
  done
done | sort -t'|' -k1,1 -f | while IFS='|' read -r keyword left right rfc num; do
  cat >> index.html << EOF
      <tr>
        <td class="left">${left}</td>
        <td class="keyword">${keyword}</td>
        <td class="right">${right}</td>
        <td class="rfc"><a href="${rfc}.html">${num}</a></td>
      </tr>
EOF
done

TIMESTAMP="$(date -u +'%Y-%m-%d %H:%MZ') ($(date +'%H:%M %Z'))"
HOSTNAME=$(hostname -s)
cat >> index.html << EOF
    </tbody>
  </table>

  <footer>
    <p>Generated by the Library of Cyberspace documentation pipeline.</p>
    <p>Node: ${HOSTNAME} | ${TIMESTAMP} | ${#RFCS[@]} RFCs</p>
    <p>Newton for the data model. Stephenson for the prose. Not Gibson.</p>
  </footer>
</body>
</html>
EOF

echo "Generated index.html with $(grep -c '<tr>' index.html) entries"
