#!/bin/zsh
# RFC Documentation Pipeline - S-expression Edition
#
# Generates all RFC formats from S-expression sources
# Source: .scm (S-expression documents)
# Output: .txt, .html, .ps
#
# This is the DSSSL-inspired pipeline:
#   S-expression source → Scheme processors → multiple outputs

set -e
setopt null_glob

cd "$(dirname "$0")"

echo "=== RFC Documentation Pipeline (S-expression) ==="
echo ""

# Discover RFCs from filesystem
discover_rfcs() {
    for f in rfc-*.scm; do
        [[ -f "$f" ]] && echo "${f%.scm}"
    done | sort -t- -k2,2n
}

RFCS=("${(@f)$(discover_rfcs)}")
echo "Discovered ${#RFCS[@]} S-expression RFCs"

# Check if source is stale
is_stale() {
    local source="$1" target="$2"
    [[ ! -f "$target" ]] && return 0
    [[ "$source" -nt "$target" ]] && return 0
    return 1
}

# Generate all formats from a single .scm source
generate_from_scm() {
    local rfc="$1"
    local generated=""

    # Check staleness against all outputs
    local need_regen=0
    is_stale "${rfc}.scm" "${rfc}.txt" && need_regen=1
    is_stale "${rfc}.scm" "${rfc}.html" && need_regen=1
    is_stale "${rfc}.scm" "${rfc}.ps" && need_regen=1

    if [[ $need_regen -eq 1 ]]; then
        # Generate all three formats in one Scheme invocation
        csi -q -e "
(load \"rfc-format.scm\")
(define doc (read-rfc \"${rfc}.scm\"))
(rfc->txt doc \"${rfc}.txt\")
(rfc->html doc \"${rfc}.html\")
(rfc->ps doc \"${rfc}.ps\")
" 2>/dev/null

        # Check what was generated
        [[ -f "${rfc}.txt" ]] && generated="${generated}txt "
        [[ -f "${rfc}.html" ]] && generated="${generated}html "
        [[ -f "${rfc}.ps" ]] && generated="${generated}ps "
    fi

    if [[ -n "$generated" ]]; then
        echo "  ${rfc}: ${generated}"
    fi
}

# Generate index.html catalog
generate_index() {
    echo "Generating index.html..."

    cat > index.html << 'HEADER'
<!DOCTYPE html>
<html lang="en" data-theme="dark">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Library of Cyberspace - RFC Index</title>
  <link rel="stylesheet" href="rfc.css">
  <style>
    body { max-width: 900px; margin: 0 auto; padding: 1rem; }
    h1 { border-bottom: 2px solid var(--accent); padding-bottom: 0.5rem; }
    table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
    th, td { padding: 0.5rem; text-align: left; border-bottom: 1px solid var(--border); }
    th { background: var(--bg-alt); }
    .formats a { margin-right: 0.5rem; }
    footer { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid var(--border); font-size: 0.9rem; color: var(--fg-dim); }
  </style>
</head>
<body>
  <h1>Library of Cyberspace - RFC Index</h1>
  <p>Request for Comments documents for the Library of Cyberspace preservation architecture.</p>
  <p><em>Generated from S-expression sources via Scheme processors.</em></p>

  <table>
    <thead>
      <tr>
        <th>RFC</th>
        <th>Title</th>
        <th>Formats</th>
      </tr>
    </thead>
    <tbody>
HEADER

    for rfc in "${RFCS[@]}"; do
        # Extract title from .scm file
        local title=$(grep -m1 "(title " "${rfc}.scm" 2>/dev/null | sed 's/.*"\\(.*\\)".*/\\1/')
        local num=$(echo "$rfc" | sed 's/rfc-0*//' | cut -d- -f1)
        local formats='<a href="'"${rfc}"'.txt">txt</a> <a href="'"${rfc}"'.html">html</a> <a href="'"${rfc}"'.ps">ps</a>'

        cat >> index.html << EOF
      <tr>
        <td>${num}</td>
        <td>${title}</td>
        <td class="formats">${formats}</td>
      </tr>
EOF
    done

    cat >> index.html << 'FOOTER'
    </tbody>
  </table>

  <footer>
    <p>Generated by the Library of Cyberspace documentation pipeline.</p>
    <p>Source: S-expressions. Processing: Scheme. Output: txt, html, ps.</p>
    <p>No markdown. No pandoc. Just Lisp.</p>
  </footer>
</body>
</html>
FOOTER

    echo "  -> index.html"
}

# Main
echo "Generating formats..."
for rfc in "${RFCS[@]}"; do
    generate_from_scm "$rfc"
done

generate_index

echo ""
echo "Done."
echo "  Sources: $(ls -1 rfc-*.scm 2>/dev/null | wc -l | tr -d ' ') .scm"
echo "  TXT:     $(ls -1 rfc-*.txt 2>/dev/null | wc -l | tr -d ' ')"
echo "  HTML:    $(ls -1 rfc-*.html 2>/dev/null | wc -l | tr -d ' ')"
echo "  PS:      $(ls -1 rfc-*.ps 2>/dev/null | wc -l | tr -d ' ')"
