#!/bin/bash
# RFC Documentation Pipeline
# Generates all RFC formats and index catalog
#
# Formats:
#   .md   - Markdown source (version control, editing)
#   .html - Web viewing (standalone)
#   .pdf  - Archival, printing
#   .txt  - Plain text (IETF tradition, universal)
#
# Future: RSS/Atom feed generation

set -e

RFCS=(
  rfc-000-manifesto
  rfc-001-replication-layer
  rfc-002-architecture
  rfc-003-audit-trail
  rfc-004-spki-authorization
  rfc-005-metadata-levels
  rfc-006-vault-architecture
  rfc-007-threshold-governance
  rfc-008-shamir-sharing
  rfc-009-library-directory
  rfc-010-federation
  rfc-011-byzantine-consensus
  rfc-012-lamport-clocks
  rfc-013-tla-specification
  rfc-014-coq-extraction
  rfc-015-versioning-rollback
  rfc-016-lazy-clustering
  rfc-017-opera
  rfc-018-sealed-archive
  rfc-019-documentation-pipeline
)

# Extract title from markdown file
get_title() {
  head -1 "$1" | sed 's/^# //'
}

# Generate individual RFC formats
generate_formats() {
  local rfc="$1"

  if [[ ! -f "${rfc}.md" ]]; then
    echo "  [skip] ${rfc}.md not found"
    return
  fi

  echo "Processing ${rfc}..."

  # HTML (standalone)
  pandoc "${rfc}.md" -o "${rfc}.html" --standalone --metadata title="" 2>/dev/null

  # PDF (xelatex with Menlo font)
  pandoc "${rfc}.md" -o "${rfc}.pdf" --pdf-engine=xelatex -V mainfont="Menlo" 2>/dev/null

  # Plain text (78 columns, IETF style)
  pandoc "${rfc}.md" -o "${rfc}.txt" --to=plain --wrap=auto --columns=78 2>/dev/null

  echo "  -> .html .pdf .txt"
}

# Generate index.html catalog
generate_index() {
  echo "Generating index.html..."

  cat > index.html << 'HEADER'
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Library of Cyberspace - RFC Index</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      max-width: 900px;
      margin: 0 auto;
      padding: 2rem;
      line-height: 1.6;
      color: #333;
    }
    h1 { border-bottom: 2px solid #333; padding-bottom: 0.5rem; }
    table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
    th, td { padding: 0.5rem; text-align: left; border-bottom: 1px solid #ddd; }
    th { background: #f5f5f5; }
    .formats a { margin-right: 0.5rem; font-size: 0.9rem; }
    .formats a:hover { text-decoration: underline; }
    footer { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #ddd; font-size: 0.9rem; color: #666; }
  </style>
</head>
<body>
  <h1>Library of Cyberspace - RFC Index</h1>
  <p>Request for Comments documents for the Library of Cyberspace preservation architecture.</p>

  <table>
    <thead>
      <tr>
        <th>RFC</th>
        <th>Title</th>
        <th>Formats</th>
      </tr>
    </thead>
    <tbody>
HEADER

  for rfc in "${RFCS[@]}"; do
    if [[ -f "${rfc}.md" ]]; then
      local title=$(get_title "${rfc}.md")
      local num=$(echo "$rfc" | sed 's/rfc-0*//' | cut -d- -f1)

      cat >> index.html << EOF
      <tr>
        <td>${num}</td>
        <td>${title}</td>
        <td class="formats">
          <a href="${rfc}.html">html</a>
          <a href="${rfc}.pdf">pdf</a>
          <a href="${rfc}.txt">txt</a>
          <a href="${rfc}.md">md</a>
        </td>
      </tr>
EOF
    fi
  done

  cat >> index.html << 'FOOTER'
    </tbody>
  </table>

  <footer>
    <p>Generated by the Library of Cyberspace documentation pipeline.</p>
    <p>All formats are canonical and preserved in the Vault.</p>
  </footer>
</body>
</html>
FOOTER

  echo "  -> index.html"
}

# Main
echo "=== RFC Documentation Pipeline ==="
echo ""

for rfc in "${RFCS[@]}"; do
  generate_formats "$rfc"
done

generate_index

echo ""
echo "Done."
echo "  HTML: $(ls *.html 2>/dev/null | wc -l | tr -d ' ')"
echo "  PDF:  $(ls *.pdf 2>/dev/null | wc -l | tr -d ' ')"
echo "  TXT:  $(ls *.txt 2>/dev/null | wc -l | tr -d ' ')"
echo "  MD:   $(ls rfc-*.md 2>/dev/null | wc -l | tr -d ' ')"
