#!/bin/sh

#
# An imp for Cyberspace
#

# Instantiate cyberspace
if [ ! -e $HOME/cyberspace ]; then
    mkdir -vp cyberspace
fi

# cp -vf "$HOME/Library/Mobile Documents/com~apple~CloudDocs/imp" "$HOME/imp"
# chmod -vf +x "$HOME/imp"
# echo "✅ Cyberspace imp armed."

scp www.yoyodyne.com:places/cyberspace/genesis $HOME/cyberspace/genesis
scp www.yoyodyne.com:places/cyberspace/genesis.tar.zst $HOME/cyberspace/genesis.tar.zst
if [ $? -eq 0 ]; then
    echo "✅ Download complete: 🌐 places/cyberspace/genesis → cyberspace/genesis"
fi

printf "Do you want to transfer to cyberspace/genesis? [y|N] "
read ans
case "$ans" in
  [yY]* )
    echo "3..2..1..🛰️"
    sh "$HOME/cyberspace/genesis"
    ;; # Appease parser
  * )
    echo "📦 Skipping transfer to cyberspace/genesis."
    ;;
esac
