#!/bin/sh



# publish-cyberspace: Upload toolset only
REMOTE=www.yoyodyne.com
REMOTE_PATH=places/cyberspace
echo "Publishing Cyberspace tools to $REMOTE..."

# Upload all tools
scp ~/bin/break-glass www.yoyodyne.com:places/cyberspace/
scp ~/bin/fetch-cyberspace www.yoyodyne.com:places/cyberspace/
scp ~/bin/fetch-cyberspace-toola www.yoyodyne.com:places/cyberspace/
scp ~/bin/freeze-genesis www.yoyodyne.com:places/cyberspace/
scp ~/bin/genesis www.yoyodyne.com:places/cyberspace/
scp ~/bin/genesis-fedora www.yoyodyne.com:places/cyberspace/
scp ~/bin/imp www.yoyodyne.com:places/cyberspace/
scp ~/bin/inspect www.yoyodyne.com:places/cyberspace/
scp ~/bin/publish-genesis www.yoyodyne.com:places/cyberspace/
scp ~/bin/publish-cyberspace www.yoyodyne.com:places/cyberspace/
scp ~/bin/singularity www.yoyodyne.com:places/cyberspace/
scp ~/bin/sync-cyberspace www.yoyodyne.com:places/cyberspace/

echo "Cyberspace tools uploaded at $(date)"
