#!/bin/sh

# publish-cyberspace: Upload toolset only
echo "Publishing Cyberspace tools..."

# Upload all tools
scp ~/bin/break-glass www.yoyodyne.com:places/cyberspace/
scp ~/bin/fetch-cyberspace www.yoyodyne.com:places/cyberspace/
scp ~/bin/freeze-genesis www.yoyodyne.com:places/cyberspace/
scp ~/bin/genesis www.yoyodyne.com:places/cyberspace/
scp ~/bin/genesis-fedora www.yoyodyne.com:places/cyberspace/
scp ~/bin/imp www.yoyodyne.com:places/cyberspace/
scp ~/bin/inspect www.yoyodyne.com:places/cyberspace/
scp ~/bin/publish-genesis www.yoyodyne.com:places/cyberspace/
scp ~/bin/publish-cyberspace www.yoyodyne.com:places/cyberspace/
scp ~/bin/singularity www.yoyodyne.com:places/cyberspace/
scp ~/bin/sync-cyberspace www.yoyodyne.com:places/cyberspace/

echo "✅ Cyberspace tools upload complete at $(date)"
