#!/bin/sh

# Upload the tools
scp ~/bin/freeze-genesis www.yoyodyne.com:places/cyberspace/
scp ~/bin/genesis www.yoyodyne.com:places/cyberspace/
scp ~/bin/imp www.yoyodyne.com:places/cyberspace/
scp ~/bin/publish-genesis www.yoyodyne.com:places/cyberspace/

# Upload the keys
scp ~/src/ssh.tar.zst www.yoyodyne.com:places/cyberspace

# Upload the place

# scp -c aes128-gcm@openssh.com ~/tmp/genesis.tar.zst.age ddp@www.yoyodyne.com:places/cyberspace/
scp -C -c aes128-ctr ~/tmp/genesis.tar.zst.age ddp@www.yoyodyne.com:places/cyberspace/
scp ~/tmp/genesis.tar.zst.age.sha256 ddp@www.yoyodyne.com:places/cyberspace/

# DO NOT leave on a public web server
#ssh www.yoyodyne.com 'sudo cp -v $HOME/genesis.tar.zst /www/yoyodyne/ddp/places/cyberspace/'

echo "✅ Upload complete: ~/tmp/genesis.tar.zst.age → 🌐 places/cyberspace/genesis.tar.zst.age at $(date)"
