#!/bin/sh

printf "Do you want to return to the void? [y|N] "
read ans
case "$ans" in
  [yY]* )
    echo "3..2..1..🛰️"
    rm -v ~/.csirc ~/.emacs ~/.gitconfig ~/.hints ~/.sbclrc ~/.tcshrc ~/.twmrc ~/.Xdefaults
    rm -rfv audio bin doc src me pics vids iCloud OneDrive cyberspace
    ;; # Appease parser
  * )
    ;;
esac




