#!/bin/sh

# sync-cyberspace
pushd ~/src/cyberspace

# Copy all tools from ~/bin
cp ~/bin/{break-glass,fetch-cyberspace,freeze-genesis,genesis,inspect,imp,publish-genesis,singularity,sync-cyberspace} .

# Copy all configs from ~/src 
cp ~/src/{.csirc,.emacs,.tcshrc,.twmrc,.gitconfig,.hints,.Xdefaults,.zshrc} .
cp ~/src/lisp/sbcl.rc .sbclrc

git add .
git status --porcelain
git diff --cached --name-only
git commit -v -m "Sync operational changes to version control $(date)"
git push

popd
