;; assertion-catalog.scm - Auto-generated kernel assertion catalog
;; Generated by extract-assertions.sh
;; DO NOT EDIT - regenerate with: ./docs/notes/extract-assertions.sh

(define *assertion-catalog*
  '(
    ;; === Instrumentation Points (session-stat!) ===
    (instrumentation bytes-in "./gossip.scm" 179)
    (instrumentation bytes-out "./gossip.scm" 169)
    (instrumentation bytes-written "./vault.scm" 653)
    (instrumentation commits "./cyberspace-repl.scm" 5034)
    (instrumentation decrypts "./vault.scm" 317)
    (instrumentation encrypts "./vault.scm" 261)
    (instrumentation federation-changes "./cyberspace-repl.scm" 5065)
    (instrumentation gossip-exchanges "./cyberspace-repl.scm" 5320)
    (instrumentation hashes "./vault.scm" 2024)
    (instrumentation mdns-messages "./mdns.scm" 128)
    (instrumentation packets-ipv "./gossip.scm" 185)
    (instrumentation peers-discovered "./cyberspace-repl.scm" 5312)
    (instrumentation queries "./cyberspace-repl.scm" 1284)
    (instrumentation reads "./vault.scm" 1347)
    (instrumentation seals "./cyberspace-repl.scm" 5035)
    (instrumentation signs "./cyberspace-repl.scm" 5045)
    (instrumentation syncs "./cyberspace-repl.scm" 1159)
    (instrumentation unlocks "./vault.scm" 330)
    (instrumentation verifies "./cyberspace-repl.scm" 5050)
    (instrumentation votes "./cyberspace-repl.scm" 1417)
    (instrumentation wormholes "./cyberspace-repl.scm" 1903)
    (instrumentation writes "./vault.scm" 652)

    ;; === Security Errors ===
    (security-error capability-amplification "./cyberspace-repl.scm" 1945)
    (security-error confidentiality-violation "./cyberspace-repl.scm" 2160)
    (security-error delegate-denied "./cyberspace-repl.scm" 2195)
    (security-error delete-denied "./cyberspace-repl.scm" 2192)
    (security-error integrity-violation "./cyberspace-repl.scm" 2164)
    (security-error no-ambient-authority "./cyberspace-repl.scm" 2181)
    (security-error read-denied "./cyberspace-repl.scm" 2186)
    (security-error secure-clear "./cyberspace-repl.scm" 2354)
    (security-error secure-clear-failed "./cyberspace-repl.scm" 2342)
    (security-error write-denied "./cyberspace-repl.scm" 2189)

    ;; === Precondition Guards ===
    (precondition directory-exists? keystore-path "./enroll.scm" 497)
    (precondition directory-exists? *board-path* "./board.scm" 53)
    (precondition directory-exists? ".forge" "./cyberspace-repl.scm" 267)
    (precondition chaotic? thing "./cyberspace-repl.scm" 809)
    (precondition attested? "./cyberspace-repl.scm" 958)
    (precondition quiescent? memo "./cyberspace-repl.scm" 1062)
    (precondition attested? "./cyberspace-repl.scm" 1602)
    (precondition attested? "./cyberspace-repl.scm" 1630)
    (precondition directory-exists? ".vault/keys" "./cyberspace-repl.scm" 3823)
    (precondition directory-exists? output-dir "./spki-keygen.scm" 83)
    (precondition directory-exists? d "./scrutinize.scm" 188)
    (precondition directory-exists? path "./keyring.scm" 76)
    (precondition directory-exists? ks-dir "./vault.scm" 247)
    (precondition keystore-exists? "./vault.scm" 301)
    (precondition directory-exists? ".vault" "./vault.scm" 421)
))

;; Summary counts
(define (assertion-summary)
  (let ((instrs (filter (lambda (a) (eq? (car a) 'instrumentation)) *assertion-catalog*))
        (errors (filter (lambda (a) (eq? (car a) 'security-error)) *assertion-catalog*))
        (guards (filter (lambda (a) (eq? (car a) 'precondition)) *assertion-catalog*)))
    `((instrumentation-points . ,(length instrs))
      (security-errors . ,(length errors))
      (precondition-guards . ,(length guards))
      (total . ,(length *assertion-catalog*)))))
