;; assertion-catalog.scm - Auto-generated kernel assertion catalog
;; Generated by extract-assertions.sh
;; DO NOT EDIT - regenerate with: ./docs/notes/extract-assertions.sh

(define *assertion-catalog*
  '(
    ;; === Instrumentation Points (session-stat!) ===
    (instrumentation bytes-in "./gossip.scm" 179)
    (instrumentation bytes-out "./gossip.scm" 169)
    (instrumentation bytes-written "./vault.scm" 653)
    (instrumentation commits "./cyberspace-repl.scm" 5020)
    (instrumentation decrypts "./vault.scm" 317)
    (instrumentation encrypts "./vault.scm" 261)
    (instrumentation federation-changes "./cyberspace-repl.scm" 5051)
    (instrumentation gossip-exchanges "./cyberspace-repl.scm" 5301)
    (instrumentation hashes "./vault.scm" 2024)
    (instrumentation mdns-messages "./mdns.scm" 128)
    (instrumentation packets-ipv "./gossip.scm" 185)
    (instrumentation peers-discovered "./cyberspace-repl.scm" 5293)
    (instrumentation queries "./cyberspace-repl.scm" 1279)
    (instrumentation reads "./vault.scm" 1347)
    (instrumentation seals "./cyberspace-repl.scm" 5021)
    (instrumentation signs "./cyberspace-repl.scm" 5031)
    (instrumentation syncs "./cyberspace-repl.scm" 1154)
    (instrumentation unlocks "./vault.scm" 330)
    (instrumentation verifies "./cyberspace-repl.scm" 5036)
    (instrumentation votes "./cyberspace-repl.scm" 1412)
    (instrumentation wormholes "./cyberspace-repl.scm" 1898)
    (instrumentation writes "./vault.scm" 652)

    ;; === Security Errors ===
    (security-error capability-amplification "./cyberspace-repl.scm" 1940)
    (security-error confidentiality-violation "./cyberspace-repl.scm" 2155)
    (security-error delegate-denied "./cyberspace-repl.scm" 2190)
    (security-error delete-denied "./cyberspace-repl.scm" 2187)
    (security-error integrity-violation "./cyberspace-repl.scm" 2159)
    (security-error no-ambient-authority "./cyberspace-repl.scm" 2176)
    (security-error read-denied "./cyberspace-repl.scm" 2181)
    (security-error secure-clear "./cyberspace-repl.scm" 2349)
    (security-error secure-clear-failed "./cyberspace-repl.scm" 2337)
    (security-error write-denied "./cyberspace-repl.scm" 2184)

    ;; === Precondition Guards ===
    (precondition directory-exists? keystore-path "./enroll.scm" 503)
    (precondition directory-exists? ".forge" "./cyberspace-repl.scm" 266)
    (precondition chaotic? thing "./cyberspace-repl.scm" 804)
    (precondition attested? "./cyberspace-repl.scm" 953)
    (precondition quiescent? memo "./cyberspace-repl.scm" 1057)
    (precondition attested? "./cyberspace-repl.scm" 1597)
    (precondition attested? "./cyberspace-repl.scm" 1625)
    (precondition directory-exists? ".vault/keys" "./cyberspace-repl.scm" 3809)
    (precondition directory-exists? output-dir "./spki-keygen.scm" 83)
    (precondition directory-exists? path "./keyring.scm" 76)
    (precondition directory-exists? ks-dir "./vault.scm" 247)
    (precondition keystore-exists? "./vault.scm" 301)
    (precondition directory-exists? ".vault" "./vault.scm" 421)
))

;; Summary counts
(define (assertion-summary)
  (let ((instrs (filter (lambda (a) (eq? (car a) 'instrumentation)) *assertion-catalog*))
        (errors (filter (lambda (a) (eq? (car a) 'security-error)) *assertion-catalog*))
        (guards (filter (lambda (a) (eq? (car a) 'precondition)) *assertion-catalog*)))
    `((instrumentation-points . ,(length instrs))
      (security-errors . ,(length errors))
      (precondition-guards . ,(length guards))
      (total . ,(length *assertion-catalog*)))))
