;; assertion-catalog.scm - Auto-generated kernel assertion catalog
;; Generated by extract-assertions.sh
;; DO NOT EDIT - regenerate with: ./docs/notes/extract-assertions.sh

(define *assertion-catalog*
  '(
    ;; === Instrumentation Points (session-stat!) ===
    (instrumentation bytes-in "./gossip.scm" 179)
    (instrumentation bytes-out "./gossip.scm" 169)
    (instrumentation bytes-written "./vault.scm" 653)
    (instrumentation commits "./cyberspace-repl.scm" 5047)
    (instrumentation decrypts "./vault.scm" 317)
    (instrumentation encrypts "./vault.scm" 261)
    (instrumentation federation-changes "./cyberspace-repl.scm" 5078)
    (instrumentation gossip-exchanges "./cyberspace-repl.scm" 5612)
    (instrumentation hashes "./vault.scm" 2083)
    (instrumentation mdns-messages "./mdns.scm" 128)
    (instrumentation packets-ipv "./gossip.scm" 185)
    (instrumentation peers-discovered "./cyberspace-repl.scm" 5604)
    (instrumentation queries "./cyberspace-repl.scm" 1306)
    (instrumentation reads "./vault.scm" 1349)
    (instrumentation seals "./cyberspace-repl.scm" 5048)
    (instrumentation signs "./cyberspace-repl.scm" 5058)
    (instrumentation syncs "./cyberspace-repl.scm" 1181)
    (instrumentation unlocks "./vault.scm" 330)
    (instrumentation verifies "./cyberspace-repl.scm" 5063)
    (instrumentation votes "./cyberspace-repl.scm" 1439)
    (instrumentation wormholes "./cyberspace-repl.scm" 1925)
    (instrumentation writes "./vault.scm" 652)

    ;; === Security Errors ===
    (security-error capability-amplification "./cyberspace-repl.scm" 1967)
    (security-error confidentiality-violation "./cyberspace-repl.scm" 2182)
    (security-error delegate-denied "./cyberspace-repl.scm" 2217)
    (security-error delete-denied "./cyberspace-repl.scm" 2214)
    (security-error integrity-violation "./cyberspace-repl.scm" 2186)
    (security-error no-ambient-authority "./cyberspace-repl.scm" 2203)
    (security-error read-denied "./cyberspace-repl.scm" 2208)
    (security-error secure-clear "./cyberspace-repl.scm" 2376)
    (security-error secure-clear-failed "./cyberspace-repl.scm" 2364)
    (security-error write-denied "./cyberspace-repl.scm" 2211)

    ;; === Precondition Guards ===
    (precondition directory-exists? keystore-path "./enroll.scm" 497)
    (precondition directory-exists? *board-path* "./board.scm" 52)
    (precondition directory-exists? ".forge" "./cyberspace-repl.scm" 287)
    (precondition chaotic? thing "./cyberspace-repl.scm" 831)
    (precondition attested? "./cyberspace-repl.scm" 980)
    (precondition quiescent? memo "./cyberspace-repl.scm" 1084)
    (precondition attested? "./cyberspace-repl.scm" 1624)
    (precondition attested? "./cyberspace-repl.scm" 1652)
    (precondition directory-exists? ".vault/keys" "./cyberspace-repl.scm" 3836)
    (precondition directory-exists? output-dir "./spki-keygen.scm" 83)
    (precondition directory-exists? path "./keyring.scm" 76)
    (precondition directory-exists? ks-dir "./vault.scm" 247)
    (precondition keystore-exists? "./vault.scm" 301)
    (precondition directory-exists? ".vault" "./vault.scm" 421)
))

;; Summary counts
(define (assertion-summary)
  (let ((instrs (filter (lambda (a) (eq? (car a) 'instrumentation)) *assertion-catalog*))
        (errors (filter (lambda (a) (eq? (car a) 'security-error)) *assertion-catalog*))
        (guards (filter (lambda (a) (eq? (car a) 'precondition)) *assertion-catalog*)))
    `((instrumentation-points . ,(length instrs))
      (security-errors . ,(length errors))
      (precondition-guards . ,(length guards))
      (total . ,(length *assertion-catalog*)))))
