#!/bin/bash
# extract-assertions.sh - Extract security assertions from cyberspace kernel
#
# Generates assertion-catalog.scm for inclusion in Memo-046
#
# Categories:
#   - Instrumentation: session-stat! calls
#   - Security errors: typed error symbols
#   - Preconditions: unless guards with error
#
# Part of the RFC generation pipeline.

set -e
cd "$(dirname "$0")/../.."

OUTPUT="docs/notes/assertion-catalog.scm"

cat > "$OUTPUT" << 'HEADER'
;; assertion-catalog.scm - Auto-generated kernel assertion catalog
;; Generated by extract-assertions.sh
;; DO NOT EDIT - regenerate with: ./docs/notes/extract-assertions.sh

(define *assertion-catalog*
  '(
HEADER

echo "    ;; === Instrumentation Points (session-stat!) ===" >> "$OUTPUT"
grep -rn "session-stat! '" --include="*.scm" 2>/dev/null | \
    grep -v "docs/notes\|\.import\.scm\|define.*session-stat" | \
    sed -n "s/\([^:]*\):\([0-9]*\):.*session-stat! '\([a-z-]*\).*/\1 \2 \3/p" | \
    sort -k3 -u | \
    while read file line stat; do
        printf '    (instrumentation %s "%s" %s)\n' "$stat" "$file" "$line" >> "$OUTPUT"
    done

echo "" >> "$OUTPUT"
echo "    ;; === Security Errors ===" >> "$OUTPUT"
grep -rn "error '[a-z-]*" --include="*.scm" 2>/dev/null | \
    grep -v "docs/notes\|eggs/\|test-" | \
    grep -E "capability|authority|violation|denied|clear|unauthorized|forbidden" | \
    sed -n "s/\([^:]*\):\([0-9]*\):.*error '\([a-z-]*\).*/\1 \2 \3/p" | \
    sort -k3 -u | \
    while read file line err; do
        printf '    (security-error %s "%s" %s)\n' "$err" "$file" "$line" >> "$OUTPUT"
    done

echo "" >> "$OUTPUT"
echo "    ;; === Precondition Guards ===" >> "$OUTPUT"
grep -rn "(unless\|(when" --include="*.scm" 2>/dev/null | \
    grep -v "docs/notes\|eggs/\|test-" | \
    grep -E "attested\?|chaotic\?|quiescent\?|keystore-exists\?|directory-exists" | \
    sed -n "s/\([^:]*\):\([0-9]*\):.*(unless (\([^)]*\)).*/\1 \2 \3/p" | \
    head -20 | \
    while read file line guard; do
        printf '    (precondition %s "%s" %s)\n' "$guard" "$file" "$line" >> "$OUTPUT"
    done

cat >> "$OUTPUT" << 'FOOTER'
))

;; Summary counts
(define (assertion-summary)
  (let ((instrs (filter (lambda (a) (eq? (car a) 'instrumentation)) *assertion-catalog*))
        (errors (filter (lambda (a) (eq? (car a) 'security-error)) *assertion-catalog*))
        (guards (filter (lambda (a) (eq? (car a) 'precondition)) *assertion-catalog*)))
    `((instrumentation-points . ,(length instrs))
      (security-errors . ,(length errors))
      (precondition-guards . ,(length guards))
      (total . ,(length *assertion-catalog*)))))
FOOTER

# Count results
INSTR=$(grep -c "^    (instrumentation " "$OUTPUT" 2>/dev/null || echo 0)
ERRORS=$(grep -c "^    (security-error " "$OUTPUT" 2>/dev/null || echo 0)
GUARDS=$(grep -c "^    (precondition " "$OUTPUT" 2>/dev/null || echo 0)
TOTAL=$((INSTR + ERRORS + GUARDS))

echo "  -> $OUTPUT"
echo "     $INSTR instrumentation, $ERRORS security errors, $GUARDS guards ($TOTAL total)"
