#!/bin/bash
# Generate Memo index with KWIC
# Auto-discovers all memo-*.txt files

# Memo namespace configuration - single source of truth
# Width increases when namespace overflows (0000-9999 -> 00000-99999)
MEMO_NUMBER_WIDTH=4

# Extract memo number from filename (preserves padding)
extract_memo_num() {
  echo "$1" | sed 's/memo-\([0-9]*\)-.*/\1/'
}

# Discover Memos from filesystem (unique basenames, sorted by number)
discover_memos() {
  shopt -s nullglob
  for f in memo-*.md memo-*.txt; do
    [[ -f "$f" ]] && echo "${f%.*}"
  done | sort -u | sort -t- -k2,2n
}

# Check for duplicate Memo numbers
check_duplicates() {
  local prev_num=""
  local prev_memo=""
  for memo in "$@"; do
    local num=$(extract_memo_num "$memo")
    if [[ -n "$prev_num" && "$num" == "$prev_num" ]]; then
      echo "WARNING: Duplicate Memo number $num:" >&2
      echo "  - $prev_memo" >&2
      echo "  - $memo" >&2
    fi
    prev_num="$num"
    prev_memo="$memo"
  done
}

# Build array from discovery
MEMOS=()
while IFS= read -r m; do
  MEMOS+=("$m")
done < <(discover_memos)

echo "Discovered ${#MEMOS[@]} Memos"
check_duplicates "${MEMOS[@]}"

STOP_WORDS="a an and are as at be by for from has have in is it of on or the to was with"

is_stop_word() {
  local word=$(echo "$1" | tr '[:upper:]' '[:lower:]')
  for stop in $STOP_WORDS; do
    [[ "$word" == "$stop" ]] && return 0
  done
  return 1
}

get_title() {
  local base="$1"
  if [[ -f "${base}.txt" ]]; then
    head -1 "${base}.txt"
  elif [[ -f "${base}.md" ]]; then
    head -1 "${base}.md" | sed 's/^# //'
  else
    echo "$base"
  fi
}

# Start HTML
cat > index.html << 'HEADER'
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Library of Cyberspace - Memo Index</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      max-width: 900px;
      margin: 0 auto;
      padding: 2rem;
      line-height: 1.6;
      color: #333;
    }
    h1 { border-bottom: 2px solid #333; padding-bottom: 0.5rem; }
    table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
    th, td { padding: 0.5rem; text-align: left; border-bottom: 1px solid #ddd; }
    th { background: #f5f5f5; }
    .formats a { margin-right: 0.5rem; }
    .kwic { font-family: monospace; font-size: 0.85rem; }
    .kwic td { padding: 0.25rem 0.5rem; white-space: nowrap; }
    .kwic .left { text-align: right; color: #666; }
    .kwic .keyword { font-weight: bold; }
    .kwic .right { text-align: left; color: #666; }
    .kwic .memo { text-align: left; }
  </style>
</head>
<body>
  <h1>Library of Cyberspace - Memo Index</h1>
  <p>Request for Comments documents for the Library of Cyberspace preservation architecture.</p>

  <table>
    <thead>
      <tr>
        <th>Memo</th>
        <th>Title</th>
        <th>Formats</th>
      </tr>
    </thead>
    <tbody>
HEADER

# Generate Memo table
for memo in "${MEMOS[@]}"; do
  title=$(get_title "$memo")
  num=$(extract_memo_num "$memo")
  formats='<a href="'"${memo}"'.txt">Text</a> <a href="'"${memo}"'.ps">PostScript</a> <a href="'"${memo}"'.html">Hypertext</a>'

  cat >> index.html << EOF
      <tr>
        <td>${num}</td>
        <td>${title}</td>
        <td class="formats">${formats}</td>
      </tr>
EOF
done

cat >> index.html << 'MIDDLE'
    </tbody>
  </table>

  <h2>Permuted Index (KWIC)</h2>
  <p>Key Word In Context index for discovery by concept.</p>
  <table class="kwic">
    <tbody>
MIDDLE

# Generate KWIC entries
for memo in "${MEMOS[@]}"; do
  title=$(get_title "$memo")
  # Strip "Memo NNNN: " prefix
  bare_title=$(echo "$title" | sed 's/^Memo [0-9]*: //')
  words=($bare_title)
  num_words=${#words[@]}

  for ((i=0; i<num_words; i++)); do
    word="${words[$i]}"
    # Skip stop words
    is_stop_word "$word" && continue

    # Build left context
    left=""
    for ((j=0; j<i; j++)); do
      left="$left${words[$j]} "
    done

    # Build right context
    right=""
    for ((j=i+1; j<num_words; j++)); do
      right="$right ${words[$j]}"
    done

    num=$(extract_memo_num "$memo")
    echo "${word}|${left}|${right}|${memo}|${num}"
  done
done | sort -t'|' -k1,1 -f | while IFS='|' read -r keyword left right m num; do
  cat >> index.html << EOF
      <tr>
        <td class="left">${left}</td>
        <td class="keyword">${keyword}</td>
        <td class="right">${right}</td>
        <td class="memo"><a href="${m}.html">${num}</a></td>
      </tr>
EOF
done

TIMESTAMP="$(date -u +'%Y-%m-%d %H:%MZ') ($(date +'%H:%M %Z'))"
HOSTNAME=$(hostname -s)
cat >> index.html << EOF
    </tbody>
  </table>

  <footer>
    <p>Generated by the Library of Cyberspace.</p>
    <p>Node: ${HOSTNAME} | ${TIMESTAMP} | ${#MEMOS[@]} Memos</p>
    <p>Newton for the data model. Stephenson for the prose. Not Gibson.</p>
  </footer>
</body>
</html>
EOF

echo "Generated index.html with $(grep -c '<tr>' index.html) entries"
