;;;; audit.import.scm - GENERATED BY CHICKEN 5.4.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'audit
      'audit
      (scheme#list)
      '((audit-init . audit#audit-init)
        (audit-append . audit#audit-append)
        (audit-verify . audit#audit-verify)
        (audit-read . audit#audit-read)
        (audit-chain . audit#audit-chain)
        (audit-by-actor . audit#audit-by-actor)
        (audit-by-action . audit#audit-by-action)
        (audit-by-timerange . audit#audit-by-timerange)
        (audit-export-sexp . audit#audit-export-sexp)
        (audit-export-human . audit#audit-export-human))
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
