;;;; crypto-ffi.import.scm - GENERATED BY CHICKEN 5.4.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'crypto-ffi
      'crypto-ffi
      (scheme#list)
      '((sodium-init . crypto-ffi#sodium-init)
        (ed25519-keypair! . crypto-ffi#ed25519-keypair!)
        (ed25519-keypair . crypto-ffi#ed25519-keypair)
        (ed25519-sign . crypto-ffi#ed25519-sign)
        (ed25519-verify . crypto-ffi#ed25519-verify)
        (ed25519-secret-to-public . crypto-ffi#ed25519-secret-to-public)
        (sha256-hash . crypto-ffi#sha256-hash)
        (sha512-hash . crypto-ffi#sha512-hash)
        (crypto-sign-publickeybytes . crypto-ffi#crypto-sign-publickeybytes)
        (crypto-sign-secretkeybytes . crypto-ffi#crypto-sign-secretkeybytes)
        (crypto-sign-bytes . crypto-ffi#crypto-sign-bytes))
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
