;;;; script.import.scm - GENERATED BY CHICKEN 5.4.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'script
      'script
      (scheme#list)
      '((sign-script . script#sign-script)
        (verify-script . script#verify-script)
        (threshold-sign-script . script#threshold-sign-script)
        (verify-threshold-script . script#verify-threshold-script)
        (script-signature? . script#script-signature?)
        (make-script-signature . script#make-script-signature)
        (signature-signer . script#signature-signer)
        (signature-value . script#signature-value)
        (signature-timestamp . script#signature-timestamp))
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
