;;;; sexp.import.scm - GENERATED BY CHICKEN 5.4.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'sexp
      'sexp
      (scheme#list)
      '((sexp-atom . sexp#sexp-atom)
        (sexp-list . sexp#sexp-list)
        (sexp-bytes . sexp#sexp-bytes)
        (sexp-atom? . sexp#sexp-atom?)
        (sexp-list? . sexp#sexp-list?)
        (sexp-bytes? . sexp#sexp-bytes?)
        (atom-value . sexp#atom-value)
        (list-items . sexp#list-items)
        (bytes-value . sexp#bytes-value)
        (parse-sexp . sexp#parse-sexp)
        (sexp->string . sexp#sexp->string)
        (sexp->string-indent . sexp#sexp->string-indent)
        (find-tag . sexp#find-tag)
        (get-tag-value . sexp#get-tag-value))
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
