;;;; vault.import.scm - GENERATED BY CHICKEN 5.4.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'vault
      'vault
      (scheme#list)
      '((seal-commit . vault#seal-commit)
        (seal-update . vault#seal-update)
        (seal-undo . vault#seal-undo)
        (seal-history . vault#seal-history)
        (seal-branch . vault#seal-branch)
        (seal-merge . vault#seal-merge)
        (seal-release . vault#seal-release)
        (seal-archive . vault#seal-archive)
        (seal-restore . vault#seal-restore)
        (seal-verify . vault#seal-verify)
        (vault-init . vault#vault-init)
        (vault-config . vault#vault-config))
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
